### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by nicolas-graves** [xatom/gpgme-with-guile#1]
Hi ! 
I might try and use the library if it still works, but I fear I would have to adapt some things. 
Can you add a license so that I know under which rules I could build on ? 

Thanks ! 
Nicolas

**Comment by nicolas-graves** [comment]
I've seen that it seems to be GPLv3+ in the descriptions. Will quickly do a pull request to add that.

**Comment by xatom** [comment]
Hi, Nicolas!

You've reminded me of this project after many years.  I merged your PR and the LICENSE file is now present.

Thank you!
